version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "No Unity build step needed. Files are already in WebGL/."
  post_build:
    commands:
      - echo "Starting S3 upload..."

      # Upload Brotli-compressed JavaScript
      - aws s3 cp WebGL/ s3://ive-asic-workbench/ --recursive \
          --exclude "*" --include "*.js.br" \
          --content-encoding br --content-type application/javascript

      # Upload Brotli-compressed WASM
      - aws s3 cp WebGL/ s3://ive-asic-workbench/ --recursive \
          --exclude "*" --include "*.wasm.br" \
          --content-encoding br --content-type application/wasm

      # Upload Brotli-compressed DATA
      - aws s3 cp WebGL/ s3://ive-asic-workbench/ --recursive \
          --exclude "*" --include "*.data.br" \
          --content-encoding br --content-type application/octet-stream

      # Upload remaining static files (HTML, JS, etc.)
      - aws s3 cp WebGL/ s3://ive-asic-workbench/ --recursive \
          --exclude "*.br"

      - echo "Upload complete."
artifacts:
  files:
    - WebGL/**/*

